/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import supermecado.Almacen;
import supermecado.Compra;
import supermecado.DetalleCompra;
import supermecado.Empleado;
import supermecado.ObjectNotFoundException;
import supermecado.Producto;

/**
 *
 * @author Polker
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private Venta ventana1 = null;
    private About info = null;
    private Almacen market = null;
//    private VentasRealizadas tablaVentas = null;
//    private Cliente customer = null; 
    public boolean logeado = false;
    private boolean ClientAlive = false;
//    private DetalleCompra detail = null;
    private Producto item = null;
    private Compra buy = null;
//    private int puntos = 0;
    private Empleado empleado = null;
    private ArrayList<DetalleCompra> detalleCompras = new ArrayList<>(); //error al iniciar la GUI por nullPointerException
    private Login windowLog = null;
//una solucion puede ser en la clase compra permitir crear una compra sin parametros
//    private ArrayList<Compra> Compras = new ArrayList<>();

//    public Principal() {
//        
//        
//    }
    public void clearUser() {
        User.setText("");

    }

    public void clearPassword() {

        Password.setText("");

    }

    public void clear() {
        User.setText("");
        Password.setText("");

    }

    public Principal(Almacen market) {
        this.market = market;
        this.info = new About();
        initComponents();
        //*****************************
        //Imagen de Fondo metodos:
        //1.  por Border
        this.Desktop.setBorder(new Background());
        //*****************************
        this.ShowVentas.addActionListener(new ActionListener() {
            private VentasRealizadas vr = null;

            public void actionPerformed(ActionEvent e) {
                if (this.vr == null) {
                    this.vr = new VentasRealizadas(market);
                    Desktop.add(this.vr);

                }
                this.vr.setVisible(true);

            }

        });

        ListenerLogueo log = new ListenerLogueo();
        this.Password.addActionListener(log);
        this.access.addActionListener(log);
        this.User.addActionListener(log);

//        if(this.windowLog==null){
//            this.windowLog = new Login(this.market);
//            Desktop.add(windowLog);
//            this.windowLog.setVisible(true);
//        }else{
//            windowLog.setVisible(true);
//        }
    }

    public void setLogeado(boolean log) {
        if (this.ventana1 == null) {
            this.ventana1 = new Venta(market);
            Desktop.add(ventana1);

        }
        ventana1.setVisible(log);
        ventana1.setLogeado(log);
        ventana1.logeado = log;

    }

    public void showVentas() {
//        if (this.tablaVentas == null) {
//            
//            this.tablaVentas = new VentasRealizadas(market);
//            Desktop.add(tablaVentas);
//        }
//
//        this.tablaVentas.setVisible(true);
//        this.tablaVentas.RefreshUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        PanelLogin = new javax.swing.JPanel();
        User = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        access = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Login = new javax.swing.JMenuItem();
        LogOut = new javax.swing.JMenuItem();
        ShowVentas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Mercado");
        setMinimumSize(new java.awt.Dimension(820, 630));

        Desktop.setBackground(new java.awt.Color(6, 129, 221));

        PanelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelLogin.setOpaque(false);

        User.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        User.setText("user");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password:");

        Password.setText("password");

        access.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        access.setText("Acceder");
        access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(access, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(access)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        Desktop.setLayer(PanelLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu3.setText("Aplicación");

        Login.setText("Iniciar Sesión");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jMenu3.add(Login);

        LogOut.setText("Cerrar Sesión");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jMenu3.add(LogOut);

        ShowVentas.setText("Mostrar Ventas");
        ShowVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowVentasActionPerformed(evt);
            }
        });
        jMenu3.add(ShowVentas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");

        jMenuItem4.setText("Acerca de...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed

    }//GEN-LAST:event_LoginActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        this.market.log = false;
        this.market.logueado = null;
        this.logeado = false;
        this.ClientAlive = false;
        setLogeado(logeado);
        ventana1.vendedor.setText("Vendedor: No Registrado");
        ventana1.inicio();
        buy = null;
        item = null;
        this.detalleCompras = new ArrayList<>(); // para liberar la lista de Detalle de compras al salir de la sesion
        ventana1.CompraTabla.updateUI();
        this.PanelLogin.setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    private void ShowVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowVentasActionPerformed
//        showVentas();

    }//GEN-LAST:event_ShowVentasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        info.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessActionPerformed

//        try {
//            Empleado empleado =null;
//            String loginEmpleado;
//            char[] passEmpleado;
//
//            loginEmpleado = User.getText().trim();
//
//            empleado = this.market.BuscarEmpleado(loginEmpleado.trim());
//            passEmpleado = Password.getPassword();
//
//            if (market.Logueo(loginEmpleado, passEmpleado)) {
//                    this.PanelLogin.setVisible(false);
//                    setLogeado(market.log);
//                    
//            } else {
//                JOptionPane.showMessageDialog(null, "Password Incorrecto");
//                clear();
//            }
//
//        } catch (ObjectNotFoundException notFound) {
//            JOptionPane.showMessageDialog(null, notFound.getMessage());
//        } catch (Exception error) {
//            JOptionPane.showMessageDialog(null, error.getMessage());
//        }
    }//GEN-LAST:event_accessActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new Principal().setVisible(true);
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem LogOut;
    private javax.swing.JMenuItem Login;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPasswordField Password;
    private javax.swing.JMenuItem ShowVentas;
    private javax.swing.JTextField User;
    private javax.swing.JButton access;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
public class ListenerLogueo implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                Empleado empleado = null;
                String loginEmpleado;
                char[] passEmpleado;

                loginEmpleado = User.getText().trim();

                empleado = market.BuscarEmpleado(loginEmpleado.trim());
                passEmpleado = Password.getPassword();

                if (market.Logueo(loginEmpleado, passEmpleado)) {
                    clear();
                    PanelLogin.setVisible(false);
                    setLogeado(market.log);

                } else {
                    JOptionPane.showMessageDialog(null, "Password Incorrecto");
                    clearPassword();
                }

            } catch (NullPointerException nullPointer) {
                JOptionPane.showMessageDialog(null, "Error: Password Vacio");
                nullPointer.printStackTrace();

            } catch (ObjectNotFoundException notFound) {
                JOptionPane.showMessageDialog(null, notFound.getMessage());
                clearUser();
            } catch (Exception error) {
                JOptionPane.showMessageDialog(null, error.getMessage());
            }

        }

    }

}
