/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.AbstractTableModel;
import supermecado.Almacen;
import supermecado.Compra;

/**
 *
 * @author Polker
 */
public class VentasRealizadas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentasRealizadas
     */
    private Almacen market = null;
    private ArrayList<Compra> compras = new ArrayList<>();
    
   
    
    public VentasRealizadas(Almacen shop) {
        
        this.market = shop;
        initComponents();
        this.addInternalFrameListener(new InternalFrameAdapter() {

            @Override
            public void internalFrameActivated(InternalFrameEvent e) {
                super.internalFrameActivated(e);
                compras = shop.getCompras();
                Ventas.updateUI();
            }
        });
        
        this.Ventas.setModel(new AbstractTableModel(){
            private String[] nombres ={"Vendedor","Cliente","Costo","Puntos Otorgados"};

            @Override
            public String getColumnName(int column){
                return this.nombres[column];
            }
            
            
            @Override
            public int getRowCount() {
                return compras.size();
            }

            @Override
            public int getColumnCount() {
                return this.nombres.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                Compra purchase = compras.get(rowIndex);
                switch(columnIndex){
                    case 0:
                        return purchase.getEmpleado().getNombres()+" "+purchase.getEmpleado().getApellidos();
                    case 1:
                        return purchase.getCliente().getNombres()+" "+purchase.getCliente().getApellidos();
                    case 2:
                        return purchase.getCostoTotal();
                    case 3:
                        return purchase.puntosCompra();
                }
                return "";
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Ventas = new javax.swing.JTable();

        Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Ventas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ventas;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
